name: Deployment to k8s
on:
  push:
    branches:
    - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Login Into Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build, Tag and Push Image to DockerHub
      id: build-image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t nicobzh/frontent-demo-app:$IMAGE_TAG .
        docker push nicobzh/frontent-demo-app:$IMAGE_TAG
        echo "::set-output name=image::nicobzh/frontent-demo-app:$IMAGE_TAG"
